### PR TITLE
Add query, username and password to session list

### PR DESCRIPTION
**Pull request by krusadellc**
Adds URL query and basic username and password to RTSP Sessions API

### CODE REVIEW

**Comment by jonra1993** [comment]
I think this could be related to this bug https://github.com/bluenviron/mediamtx/issues/2701

**Comment by krusadellc** [comment]
@jonra1993 it's not related to that bug.
This PR just adds query params and username/password to the RTSP List Sessions API

**Comment by krusadellc** [comment]
@aler9 can you please take a look?

**Comment by aler9** [comment]
Hello, username and password must not be saved or displayed publicly, even to administrators, since it constitutes a security issue. Adding the query is a good idea. Therefore:

* remove username and password from `APIRTSPSession`
* add query to `APIRTMPConn`, `APIWebRTCSession` too

**Comment by aler9** [comment]
Superseded by #2844

**Pull request closed without merging**
