### PR TITLE
webrtc: implement the whep http delete method

### PR DESCRIPTION
**Pull request by rgl**
this actually does nothing more than returning OK to satisfy the [whep.js `DELETE` method](https://github.com/medooze/whip-whep-js/blob/v1.0.3/whep.js#L481-L485) as mentioned in https://github.com/bluenviron/mediamtx/pull/2453.

### CODE REVIEW

**Comment by aler9** [comment]
Hello, i'd like to avoid merging workarounds and instead merge complete implementations. The DELETE method in WHEP has the role of terminating a session, by using a session identifier, that is set by the server through POST responses, through the Location header.

The server currently doesn't put the session identifier (secret) into the Location header, but puts it into the ETag header, which is compatible with PATCH but not with DELETE. Therefore, a complete TODO list for implementing this feature is:

1. move the session secret from the `Etag` to the `Location` header, after the path name (`/mypath/whip/secret`) and adjust current endpoints (POST and PATCH) in order to support this change. The `ETag` header on the other hand has to be set to `*` according to the specification.
2. Add the `DELETE` endpoint and use it to terminate the WebRTC session, by using the secret.

Examples of POST and PATCH requests that make use of the Location and ETag header are here: https://datatracker.ietf.org/doc/draft-ietf-wish-whip/

**Comment by rgl** [comment]
@aler9 please check it now.

I need your help to understand how to actually implement the `DELETE` method.

I also think that `secret` should be renamed to something else. Maybe `sessionId`? OTOH, there is an `Id` header flowing around, which I'm not sure why its needed, and maybe it not needed anymore?

**Comment by aler9** [comment]
> I also think that secret should be renamed to something else. Maybe sessionId? OTOH, there is an Id header flowing around, which I'm not sure why its needed, and maybe it not needed anymore?

This is a good question - the difference between secret and ID is that the latter is printed in logs. If we store the secret in logs or use the same variable for secret and ID, we would create a security issue, since anyone able to access logs would be able to hijack sessions.

**Comment by rgl** [comment]
> > I also think that secret should be renamed to something else. Maybe sessionId? OTOH, there is an Id header flowing around, which I'm not sure why its needed, and maybe it not needed anymore?
> 
> This is a good question - the difference between secret and ID is that the latter is printed in logs. If we store the secret in logs or use the same variable for secret and ID, we would create a security issue, since anyone able to access logs would be able to hijack sessions.

With this pr, the secret is now effectively in the url, which we should assume will end up in the logs. Maybe the url should use the ID instead?

**Comment by aler9** [comment]
i finished the implementation and merged, thanks!

**Comment by aler9** [comment]
added in v1.2.1

**Pull request merged**
