### PR TITLE
basic auth credentials for api

### PR DESCRIPTION
**Pull request by andrew-ld**

### CODE REVIEW

**Comment by aler9** [comment]
Hello there are two possible ways to protect the API listener:

* not protecting the API at all, add a reverse proxy before it and let the reverse proxy handle the authentication.
* protecting the API, but i think that basic auth will not be enough for a lot of users that will ask for more advanced authentication techniques (separate credentials / JWT / external authentication)

We can certainly work towards the second approach, but keep in mind that handling security directly is not a "best practice" approach since there's a high risk of causing security issues. In my work i always try to avoid developing security components directly, i generally use a series of rugged security components (identity servers, gateways, WFAs, etc) and i put them before my services.

Anyway, we can certainly add a basic security layer to the server too, but i think that basic authentication will not be enough.

**Comment by andrew-ld** [comment]
having a simple level of protection like basic auth would be useful, it would avoid adding additional software such as reverse proxy and its maintenance will still remain almost zero cost since everything is implemented by gin

**Comment by aler9** [comment]
@eravellaSC i'm working on an authentication system that will support explicit credentials, external authentication or JWTs along the entire server, including paths and API.

In the meanwhile, in order to protect the API, you can use a reverse proxy.

**Comment by t3therdev** [comment]
Hi @aler9 any update on this.

**Comment by andrew-ld** [comment]
the implementation of jwt seems like something that is very time consuming, many people simply want to block requests to the api via basic auth, this solution however remains very simple to maintain and solves many of the cases

**Comment by aler9** [comment]
replaced by #3081

**Pull request closed without merging**
