### PR TITLE
Update README.md - added protocol in basic usage section for gstreamer

### PR DESCRIPTION
**Pull request by asheshstha**
Added `protocols=tcp` in basic usage section of gstreamer

### CODE REVIEW

**Comment by aler9** [comment]
Forcing TCP is not mandatory, differences between transport protocols are explained in the "RTSP specific features" section.

**Comment by aler9** [comment]
When the server is started with MTX_PROTOCOLS=tcp, there's no need to set protocols=tcp in GStreamer since it is set automatically.

**Comment by asheshstha** [comment]
My commands:

``` bash
docker run --rm -it -e MTX_PROTOCOLS=tcp -p 8554:8554 -p 1935:1935 -p 8888:8888 -p 8889:8889 -p 8890:8890/udp bluenviron/mediamtx
```

``` bash
# works
gst-launch-1.0 \
rtspclientsink protocols=tcp name=s location=rtsp://localhost:8554/stream \
filesrc location="${videosrc}" ! qtdemux name=d \
d.video_0 ! queue ! s.sink_0 \
d.audio_0 ! queue ! s.sink_1
```

``` bash
#doesn't work
gst-launch-1.0 \
rtspclientsink name=s location=rtsp://localhost:8554/stream \
filesrc location="${videosrc}" ! qtdemux name=d \
d.video_0 ! queue ! s.sink_0 \
d.audio_0 ! queue ! s.sink_1
```

``` 
rtspclientsink name=s location=rtsp://localhost:8554/stream \
filesrc location="${videosrc}" ! qtdemux name=d \
d.video_0 ! queue ! s.sink_0 \
d.audio_0 ! queue ! s.sink_1
Setting pipeline to PAUSED ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://localhost:8554/stream
Pipeline is PREROLLED ...
Prerolled, waiting for progress to finish...
Progress: (open) Retrieving server options
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending RECORD request
Progress: (record) Sending server stream info
Progress: (request) SETUP stream 1
Redistribute latency...
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstRTSPClientSink:s: Could not get/set settings from/on resource.
Additional debug info:
../gst/rtsp-sink/gstrtspclientsink.c(4258): gst_rtsp_client_sink_setup_streams (): /GstPipeline:pipeline0/GstRTSPClientSink:s:
Could not setup transport.
Execution ended after 0:00:00.015111794
Setting pipeline to NULL ...
Freeing pipeline
```

**Comment by aler9** [comment]
@asheshstha it seems that at the moment rtspclientsink is unable to automatically switch to TCP. Issue, explanation and workaround are here: #2257

**Pull request closed without merging**
