### PR TITLE
implement native recording (#1399)

### LINKED ISSUE #1399: Implement native stream recording into the server
## Describe the feature

Implement native stream recording into the server in order to replace ffmpeg and provide a complete NVR solution.

### PR DESCRIPTION
**Pull request by aler9**
Fixes #1399

## TODO

* [x] support AV1 tracks
* [x] support VP9 tracks
* <s>[ ] support VP8 tracks</s>
* [X] support H265 tracks
* [X] support H264 tracks
* [X] support MPEG-4 video tracks
* [X] support MPEG-1 video tracks
<s>* [ ] support M-JPEG tracks</s>
* [X] support Opus tracks  
* [X] support MPEG-4 audio tracks
* [x] support MPEG-1 audio tracks
<s>* [ ] support G722 tracks</s>
<s>* [ ] support G711 tracks</s>
<s>* [ ] support LPCM tracks </s>
* [x] ability to disable cleaner
* [x] ability to disable recording for some paths
* [x] add tests

## Usage

The recording format is fMP4, since it satisfies most requirements:
* it is fault tolerant
* it can be read by most players and browsers

All parameters are in the configuration file:

```yml
# Record streams to disk.
record: no
# Path of recording segments.
# Extension is added automatically.
# Available variables are %path (path name), %Y %m %d %H %M %S (time in strftime format)
recordPath: ./recordings/%path/%Y-%m-%d_%H-%M-%S
# Format of recorded segments.
# Currently the only available format is fmp4 (fragmented MP4).
recordFormat: fmp4
# fMP4 files are concatenation of small MP4 files (parts), each with this duration.
# When a system failure occurs, the last part of a recording is lost.
# Therefore, the part duration is equal to the RPO (recovery point objective).
# Increasing it decreases segment size, decreasing it decreases the RPO.
recordPartDuration: 100ms
# Minimum duration of each segment.
recordSegmentDuration: 1h
# Delete segments after this threshold.
recordDeleteAfter: 24h
```

## Nightly binaries

[mediamtx_v1.0.0-33-g2bfdc21_darwin_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12448708/mediamtx_v1.0.0-33-g2bfdc21_darwin_amd64.tar.gz)
[mediamtx_v1.0.0-33-g2bfdc21_darwin_arm64.tar.gz](https://github.com/bluenviron/mediamtx/files/12448709/mediamtx_v1.0.0-33-g2bfdc21_darwin_arm64.tar.gz)
[mediamtx_v1.0.0-33-g2bfdc21_linux_amd64.tar.gz](https://github.com/bluenviron/mediamtx/files/12448711/mediamtx_v1.0.0-33-g2bfdc21_linux_amd64.tar.gz)
[mediamtx_v1.0.0-33-g2bfdc21_linux_arm64v8.tar.gz](https://github.com/bluenviron/mediamtx/files/12448713/mediamtx_v1.0.0-33-g2bfdc21_linux_arm64v8.tar.gz)
[mediamtx_v1.0.0-33-g2bfdc21_linux_armv6.tar.gz](https://github.com/bluenviron/mediamtx/files/12448714/mediamtx_v1.0.0-33-g2bfdc21_linux_armv6.tar.gz)
[mediamtx_v1.0.0-33-g2bfdc21_linux_armv7.tar.gz](https://github.com/bluenviron/mediamtx/files/12448715/mediamtx_v1.0.0-33-g2bfdc21_linux_armv7.tar.gz)
[mediamtx_v1.0.0-33-g2bfdc21_windows_amd64.zip](https://github.com/bluenviron/mediamtx/files/12448716/mediamtx_v1.0.0-33-g2bfdc21_windows_amd64.zip)

### CODE REVIEW

**Comment by pikachu937** [comment]
Greetings.

A very joyful and significant event. But still, I would like to clarify whether you plan to implement not only fmp4, but also mpegts format, as well as the ability to turn off the audio track, balance recording between mount points (save video files) and the ability to disable recording for some streams?

Thank you, you are the best.

**Comment by pikachu937** [comment]
I forgot to ask about the parameter:
```
recordDeleteAfter: 24h
```
How to disable deletion?

**Comment by aler9** [comment]
Hello @pikachu937, 

> you plan to implement not only fmp4, but also mpegts format

MPEG-TS support can be added in the future, by me or by anyone else through a PR. I chose to focus on fMP4 because it's browser-compatible (while MPEG-TS is not) and since the next step is developing playback API, i would like this API to return browser-compatible videos.

> the ability to turn off the audio track

No. If you want to remove audio, you can create a reader that reads from a path, removes audio and republishes the stream to another path.

> balance recording between mount points

No, load balancing can be achieved by using multiple instances of the server, while fauly tolerancy can be achieved by deploying the server inside Kubernetes with a storage plugin like Longhorn or GlusterFS or a hardware solution like a SAN. Nowadays load balancing and fault tolerancy are delegated to the infrastructure (K8s), there's no need to natively implement them.

> ability to disable recording for some streams

yes, this will be done. The recording system is centralized in order clean up expired recordings regardless of the fact that a path is running or not.

> How to disable deletion

we can also add this, even though i don't recommend it.

**Comment by pikachu937** [comment]
Hello

> MPEG-TS support can be added in the future, by me or by anyone else through a PR. I chose to focus on fMP4 because it's browser-compatible (while MPEG-TS is not) and since the next step is developing playback API, i would like this API to return browser-compatible videos.

it would be very nice to see the implementation of mpegts

> No. If you want to remove audio, you can create a reader that reads from a path, removes audio and republishes the stream to another path.

I asked about turning off the audio track when saving, and not when broadcasting.

> No, load balancing can be achieved by using multiple instances of the server, while fauly tolerancy can be achieved by deploying the server inside Kubernetes with a storage plugin like Longhorn or GlusterFS or a hardware solution like a SAN. Nowadays load balancing and fault tolerancy are delegated to the infrastructure (K8s), there's no need to natively implement them.

hmm... you propose to outsource this function, but it will work many times faster if implemented (inside the server)

> we can also add this, even though i don't recommend it.

I keep records from 7 to 60 days and I myself regulate when to delete them

Will you implement adding work with a database to save metadata on records?

**Pull request merged**
