### PR TITLE
add playback server (#2452)

### PR DESCRIPTION
**Pull request by aler9**
This adds a playback server that allows to download existing recordings.

Sub-features:
* Recordings are seekable by absolute timestamp
* playback starts from the first available frame after the timestamp and goes on until a given duration
* Recording segments are automatically concatenated and remuxed into a single file
* Multiple tracks are supported, all codecs already supported by the recording feature are supported by the playback server too
* The API is natively compatible with any browser and the endpoint can be inserted directly into an HTML video tag

## Usage

Enable the playback server in the configuration file:

```yml
playback: yes
playbackAddress: :9996
```

Open the URL in the browser:

```
http://localhost:9996/get?path=[mypath]&start=[start_date]&duration=[duration]&format=[format]
```

Where:

* `[mypath]` is the path name
* `[start_date]` is the start date in RFC3336 format
* `[duration]` is the maximum duration of the recording in Golang format (i.e. 20s, 20h)
* `[format]` must be `fmp4`

All parameters must be [url-encoded](https://www.urlencoder.org/).

For instance:

```
http://localhost:9996/get?path=stream2&start=2024-01-14T16%3A33%3A17%2B00%3A00&duration=200s&format=fmp4
```

## Nightly binaries

https://github.com/bluenviron/mediamtx/actions/runs/7521944954

(click on "artifacts", "binaries")

## Todo

* [x] add tests
* [x] update README

### CODE REVIEW

**Comment by eravellaSC** [comment]
I can close #2901 right?

**Comment by aler9** [comment]
@eravellaSC your PR implements management of recording segments, while this PR implements downloading of recording segments - they're two distinct features, if you complete your PR it can be merged too.

**Comment by eravellaSC** [comment]
@aler9 Oh I am sorry I thought the features of #2901 were going to be added in this PR. I'll finish mine.

**Comment by pikachu937** [comment]
Hello. You are best, again.
Format only fmp4? You later plane add mpegts(may be playlist hls)?

**Comment by t3therdev** [comment]
Hi All, this looks very promising. Is it possible to add some layer of authentication security to this? Such as the read user/pass we do on HLS, etc? 

Great works as always @aler9 , thank you.

**Comment by t3therdev** [comment]
@aler9 testing, seems time format needs to be in rfc3336 format?
https://it-tools.tech/date-converter
2024-01-16T23:18:11-05:00 (but url encoded) seems to work 2024-01-16T23%3A08%3A41-05%3A00

**Comment by aler9** [comment]
Hello everyone,

> Format only fmp4? You later plane add mpegts(may be playlist hls)?

Regarding MPEG-TS, this can be added either my me or by another contributor.

Regarding serving recordings in HLS format, i developed that feature for a commercial project in the past, but i can't see any advantage with respect to returning files that can be natively inserted into \<video> tags. Maybe the only advantage lies in the ability of providing both the recorded stream and the live one into the same page, this might be interesting, but i'm not sure on how to manage eventual gaps.

> Is it possible to add some layer of authentication security to this? Such as the read user/pass we do on HLS, etc?

Yes, my idea is to add an authentication layer that is shared among all the services exposed by MediaMTX, including all protocols and the API, and to let the user decide the authentication mechanism to use, by chosing between credentials hardcoded in the configuration file, external endpoints and JWTs.

> seems time format needs to be in RFC3339 format?

yes, it's the standard Golang way to parse dates from strings, it's documented in lots of places.

**Comment by t3therdev** [comment]
@aler9 thanks for the update. Do you know what release this will be planned to be in?

**Comment by t3therdev** [comment]
@aler9 how does the api request for playback start time work? is it looking for the file names? i didn't review the code yet, but just wanted to see how the request knows if there is video.

**Pull request merged**
