### PR TITLE
Add database and record audio parametrs

### PR DESCRIPTION
**Pull request by major1ink**
Added functionality:
Entering information about saved files into the database (PostgreSQL).
Ability to disable audio in saved files.

The configuration file has the ability to disable/enable work with the database.

Algorithm:
When a new file is created, information about the file is entered into the database. Later, when a file segment is closed, the file information is updated in the database.
If, after creating the file, the information could not be entered into the database, the created file is deleted.
This functionality is implemented for fmp4 and mpegts.

With the recordAudio: no parameter, audio format packets will be skipped to be saved to a file, but the audio stream will not be changed in the broadcast itself.

### CODE REVIEW

**Comment by pikachu937** [comment]
Please accept

**Comment by aler9** [comment]
Hello, binding the server to PostgreSQL in this way has several disadvantages:

* this adds a mandatory, additional layer (the database) that is not necessary and unwanted by most users, in particular by the ones with limited computational capabilities
* this binds the server with PostgreSQL only, which is not ideal for all scenarios
* this delegates the state of a single instance to a database in an unidirectional way, making scaling impossible and greatly complicating the implementation of #998
* this adds an additional dependency that increases maintenance efforts, executable size and building time
* delegation of state to the database is not complete, but involves recordings only, thus a much bigger effort would be required in order to port all existing features to the database
* all the features added in this PR can already be implemented by using hooks, with no particular overhead

If you want to build a solution that involves PostgreSQL and video-only recording, my advice is to use hooks in order to populate your database of choice and to generate video-only streams.

**Comment by pikachu937** [comment]
Greetings.
>> in this way has several disadvantages

Once you also talked about the built-in recording function, but later you implemented it. 

>> this adds a mandatory, additional layer (the database) that is not necessary and unwanted by most users, in particular by the ones with limited computational capabilities

Using the database is optional, so users with limited computing capabilities will not lose anything; you can work with or without the database enabled.

>> this binds the server with PostgreSQL only, which is not ideal for all scenarios

Regarding the connection only with Postgresql, no one forbids adding support for other databases.

>> this delegates the state of a single instance to a database in an unidirectional way

What else would you like to delegate to the database, what functions?

>>scaling impossible and greatly complicating the implementation of #998

This functionality will not affect the scaling in any way, since recording in any case occurs on the node on which the stream is published.

>> all the features added in this PR can already be implemented by using hooks, with no particular overhead

Using hooks to work with a database is not always convenient, so a request for extending functionality #1681 was created, which you approved and marked as an improvement, which was implemented in this commit.

**Comment by moenodedev** [comment]
You could store all your settings in a database then make a script that writes the yaml file and restarts the server. Or the script could perform API calls.

**Pull request closed without merging**
